EnemiesLeft = 0
AliveAllies = 0
DeadAllies = 0
RescuedAllies = 0
VipName = "VIP"
ActiveSystem = false
VipdClientPlayers = { }
VipdMenu = { }
VipdWeapons = { }
VipdEnemyPositions = { }
VipdRadar = false